### ISSUE TITLE
BUG: Decouverte de case sans mine voisine

### ISSUE THREAD

**Issue by SMoraisDev** [UEVE-DLL-2024-2025/DLL#2]
Si le joueur découvre la case 0 0 alors que celle-ci n'est pas minée et n'a pas de mines voisines, l'exception suivante est levée:

```shell
Traceback (most recent call last):
  File "C:\Users\Billy\Exam\demineur.py", line 68, in <module>
    jeu.jouer()
  File "C:\Users\Billy\Exam\demineur.py", line 62, in jouer
    self.decouvrir_cases(x, y)
  File "C:\Users\Billy\Exam\demineur.py", line 46, in decouvrir_cases
    self.decouvrir_cases(x - 1, y)
  ...
  File "C:\Users\Billy\Exam\demineur.py", line 40, in decouvrir_cases
    if self.grille_visible[y][x] != '.':
IndexError: list index out of range
```

**Comment by RayaneLark** [comment]
Bonjour, pouvez vous m'assigner cette issue monsieur ?
